services:
  python-genai:
    build:
      context: ./py-genai
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - PORT=8080
      - LOG_LEVEL=DEBUG
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./py-genai:/app

networks:
  default:
    name: hello-genai-network
    driver: bridge
